# Generated by Django 5.0.1 on 2024-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinning_wheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelitem',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
