# Generated by Django 5.0.1 on 2024-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinning_wheel', '0002_wheelitem_is_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelitem',
            name='is_chosen',
        ),
        migrations.AddField(
            model_name='wheelitem',
            name='include_in_wheel',
            field=models.BooleanField(default=True),
        ),
    ]
