# Generated by Django 5.0.1 on 2024-02-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='answers',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
